movie_library/routes.py
# This code defines a Flask Blueprint to create a web application for movie watchlist.
# It contains routes for registering a new user, logging in, viewing and adding movies to the user's watchlist, and
# logging out.

# Importing necessary modules
import functools
import uuid
import datetime
from dataclasses import asdict
from flask import Blueprint, current_app, flash, redirect, render_template, session, url_for, request, app
# Importing form and model classes from the movie_library module
from movie_library.forms import LoginForm, RegisterForm, MovieForm, ExtendedMovieForm
from movie_library.models import User, Movie
# Importing the password hashing library
from passlib.hash import pbkdf2_sha256

# Creating a Blueprint object for the pages module
# The "pages" blueprint will use the templates and static folders in the same directory as this file
pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


# Defining a decorator for routes that require login
def login_required(route):
    # Wrapping the original route with the additional functionality to check for a valid login
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            # If there is no email in the session, redirect to the login page
            return redirect(url_for(".login"))
        # If the email is in the session, call the original route
        # elif # check if user is in database with email and if not session destroy and then redirect to login
        else:
            return route(*args, **kwargs)

    return route_wrapper


# Route for the main page, requires login
@pages.route("/")
@login_required
def index():
    # Fetch the user data from the database using the email stored in the session
    user_data = current_app.db.user.find_one({"email": session["email"]})
    # Create a User object from the fetched data
    user = User(**user_data)

    # Fetch the movie data
    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})
    movies = [Movie(**movie) for movie in movie_data]

    # Render the index template with the title and the list of movies
    return render_template(
        "index.html",
        title="Movies Watchlist",
        movies_data=movies,
    )


# Route for registering a new user
@pages.route("/register", methods=["POST", "GET"])
def register():
    # Redirect to the main page if the user is already logged in
    if session.get("email"):
        return redirect(url_for(".index"))

    # Create a form object for registering a new user
    form = RegisterForm()

    if form.validate_on_submit():  # Check if the form has been submitted and all required fields are valid
        # Create a new User object with the form data
        user = User(
            _id=uuid.uuid4().hex,  # Generate a unique identifier for the user using UUID
            email=form.email.data,  # Get the email from the form data
            password=pbkdf2_sha256.hash(form.password.data),  # Hash the password using pbkdf2_sha256
        )
        # Insert the user object into the "user" collection in the database
        current_app.db.user.insert_one(asdict(user))

        # Display a success message to the user
        flash("User registered successfully", "success")

        # Redirect the user to the login page
        return redirect(url_for(".login"))

    # If the form is not valid or has not been submitted yet, render the register template
    return render_template(
        "register.html", title="Movies Watchlist - Register", form=form
    )


# This is a Flask route for handling the login functionality
@pages.route("/login", methods=["GET", "POST"])
def login():
    # If a user is already logged in, redirect them to the index page
    if session.get("email"):
        return redirect(url_for(".index"))

    # Create a form instance for handling login credentials
    form = LoginForm()

    # If the form is submitted and passes validation
    if form.validate_on_submit():
        # Search for the user in the database
        user_data = current_app.db.user.find_one({"email": form.email.data})
        # If the user is not found, display an error message
        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))

        # Create a user object from the data retrieved from the database
        user = User(**user_data)

        # Verify the user password
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            # Store the user ID and email in the session
            session["user_id"] = user._id
            session["email"] = user.email

            # Redirect the user to the index page
            return redirect(url_for(".index"))

        # If the password is incorrect, display an error message
        flash("Login credentials not correct", category="danger")

    # Render the login template
    return render_template("login.html", title="Movies Watchlist - Login", form=form)


# This is a Flask route for adding a new movie

@pages.route("/add", methods=["GET", "POST"])
# Require a user to be logged in to access this route
@login_required
def add_movie():
    # Create a form instance for adding movie information
    form = MovieForm()

    # If the form is submitted and passes validation
    if form.validate_on_submit():
        # Create a movie object from the form data
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )

        # Insert the movie into the database
        current_app.db.movie.insert_one(asdict(movie))

        # Add the movie to the list of movies for the current user
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )

        # Redirect the user to the movie's detail page
        return redirect(url_for(".movie", _id=movie._id))

    # Render the template for adding a new movie
    return render_template(
        "new_movie.html", title="Movies Watchlist - Add Movie", form=form
    )


# This is a Flask route for logging out a user

@pages.route("/logout/")
def logout():
    # Save the current theme, so it can be restored after the session is cleared
    current_theme = session.get("theme")

    # Clear the session data
    session.clear()

    # Restore the current theme to the session
    session["theme"] = current_theme

    # Redirect the user to the login page
    return redirect(url_for(".login"))


# This is a Flask route for displaying movie details

@pages.get("/movie/<string:_id>")
def movie(_id: str):
    # Retrieve the movie data from the database
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))

    # Render the template for displaying movie details
    return render_template("movie_details.html", movie=movie)


# This is a Flask route for editing a movie

@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    # Retrieve the movie data from the database
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))

    # Create an instance of the extended movie form with the movie data
    form = ExtendedMovieForm(obj=movie)

    # Check if the form has been submitted and is valid
    if form.validate_on_submit():
        # Update the movie data with the form data
        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data

        # Update the movie data in the database
        current_app.db.movie.update_one({"_id": movie._id}, {"$set": asdict(movie)})

        # Redirect the user to the movie details page
        return redirect(url_for(".movie", _id=movie._id))

    # Render the template for the movie form with the movie data and form
    # If the form has not been submitted or is not valid, the function renders the "movie_form.html" template
    # with the movie data and form, allowing the user to edit the movie details.
    return render_template("movie_form.html", movie=movie, form=form)


# Route to set when you watched a movie
@pages.get("/movie/<string:_id>/watch")
@login_required  # User must be logged in to access this route
def watch_today(_id):
    # Update the movie document in the database to set the last_watched field to the current date
    current_app.db.movie.update_one(
        {"_id": _id}, {"$set": {"last_watched": datetime.datetime.today()}}
    )

    # Redirect to the movie page
    return redirect(url_for(".movie", _id=_id))


# Route to rate a movie
@pages.get("/movie/<string:_id>/rate")  # This route is triggered on a GET request to the endpoint "/movie/<_id>/rate"
@login_required  # Require that the user is logged in to access this route
def rate_movie(_id):  # The view function takes a single argument, the movie _id
    # Get the rating value from the query parameters of the GET request
    # The view function, named rate_movie, takes a single argument _id, which is a string passed as a part of the URL.
    # The <string:_id> syntax in the route is a template variable, and it tells Flask to capture the value of the string
    # that appears in that position in the URL and pass it to the view function as an argument.
    rating = int(request.args.get("rating"))

    # Update the movie document in the database with the matching _id
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})

    # Redirect the user to the movie page for the movie with the given _id
    return redirect(url_for(".movie", _id=_id))


# Route to toggle the theme
@pages.get("/toggle-theme")
def toggle_theme():

movie_library/templates/index.html
{% extends "layout.html" %}

{% block head_content %}
    <!-- Include CSS file for the movies table -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movies.css') }}"/>
{% endblock %}

{% block main_content %}
    <!-- Check if movies_data variable is set -->
    {%- if movies_data %}
        <!-- Create a table for movie information -->
        <table class="table">
            <!-- Group columns for styling -->
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            <!-- Table header -->
            <thead>
            <tr class="table__header">
                <th class="table__cell table__cell--header">Title</th>
                <th class="table__cell table__cell--header">Release Date</th>
                <th class="table__cell table__cell--header"></th>
            </tr>
            </thead>
            <!-- Table body -->
            <tbody>
            <!-- Loop through movies in the movies_data variable and display information for each movie -->
            {% for movie in movies_data %}
                <tr>
                    <td class="table__cell">
                        <!-- Display movie title -->
                        <p class="table__movieTitle">{{ movie.title }}</p>
                        <!-- Display movie director -->
                        <p class="table__movieDirector">By {{ movie.director }}</p>
                    </td>
                    <!-- Display movie release year -->
                    <td class="table__cell">{{ movie.year }}</td>
                    <!-- Link to view movie details -->
                    <td class="table__cell">
                        <a href="{{ url_for('pages.movie', _id=movie._id) }}" class="table__link">View</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <!-- If there are no movies in the movies_data variable -->
    {% else %}
        <!-- Display a message indicating there are no movies added -->
        <p class="table__empty">You haven't added any movies yet.
            <!-- Link to add a movie -->
            <a href="{{ url_for('pages.add_movie') }}" class="link">Add one!</a>
        </p>
    {% endif %}

    <!-- Link to add a movie -->
    <a href="{{ url_for('pages.add_movie') }}" class="button button--add">
        <!-- Add button symbol -->
        <span>+</span>
    </a>
{% endblock %}

movie_library/templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>

    <body>
        {{ header(session.get("email"), session.get("theme")) }}

        <main class="main">
            {% block main_content %} {% endblock %}
        </main>

        {{ footer() }}
    </body>
</html>

movie_library/templates/login.html
<!-- This line of code includes the "fields.html" file from the macros directory. -->
{% from "macros/fields.html" import render_text_field %}

<!-- This line of code extends the "layout.html" file to reuse its code. -->
{% extends "layout.html" %}

<!-- This block of code adds a link to a stylesheet for the form. -->
{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

<!-- This block of code contains the main content of the login form. -->
{% block main_content %}

    <!-- This form has a "login" name and uses the "post" method to submit data. -->
    <form name="login" method="post" novalidate class="form">

        <!-- This code displays any flash messages. -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <!-- This div container holds the form inputs. -->
        <div class="form__container">
            <!-- This line of code displays the hidden form tag. -->
            {{ form.hidden_tag() }}

            <!-- These lines of code display the email and password fields. -->
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}

            <!-- This text provides a link to register for a new account. -->
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>

            <!-- This div contains the submit button. -->
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movie_details.css') }}"/>
{% endblock %}

{% block main_content %}
    <div class="container">
        <header class="movie__header">
            <div class="header__row">
                <div class="movie__name">
                    <h1>{{ movie.title }}</h1>
                    <div class="movie__rating">
                        {% for i in range(5) %}
                            <a class="rating__link" href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}">
                                {{ star("star " + ("star--filled" if movie.rating > i else "")) }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="movie__watched">
                    {% if movie.last_watched %}
                        <p>
                            Last watched: <a href="{{ url_for('pages.watch_today', _id=movie._id) }}"
                                             class="watched__link">
                            <time datetime="{{ movie.last_watched }}">{{ movie.last_watched.strftime("%d %b %Y") }}</time>
                        </a>
                        </p>
                    {% else %}
                        <p><a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">Not watched
                            yet</a></p>
                    {% endif %}
                    <a class="movie__edit"
                       href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Edit {{ pencil("pencil") }}</a>
                </div>
            </div>
            <div class="header__row">
                <ul class="movie__tags">
                    {% for tag in movie.tags %}
                        <li class="movie__tag">{{ tag }}</li>
                    {% endfor %}
                </ul>
            </div>
        </header>
        {% if movie.video_link %}
            <iframe
                    class="movie__video"
                    src="{{ movie.video_link }}"
                    title="YouTube video player"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>
            </iframe>
        {% endif %}

        {% if movie.description %}
            <p class="movie__description">{{ movie.description }}</p>
        {% else %}
            <p class="movie__description">No description yet. <a class="link"
                                                                 href="{{ url_for('pages.edit_movie', _id=movie._id) }}">
                Add one?</a></p>
        {% endif %}

        <div class="movie__meta">
            {% if movie.cast %}
                <div class="movie__casting">
                    <h2>Casting</h2>
                    <ul class="list">
                        {% for actor in movie.cast %}
                            <li class="list__item">{{ actor }}</li>
                        {% endfor %}
                        <ul>
                </div>
            {% endif %}
            {% if movie.series | length %}
                <div class="movie__series">
                    <h2>Series</h2>
                    <ul class="list">
                        {% for movie_in_series in movie.series %}
                            <li class="list__item">{{ movie_in_series }}</li>
                        {% endfor %}
                        <ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

movie_library/templates/movie_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <!-- Add a stylesheet for forms -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}"/>
{% endblock %}

{% block main_content %}
    <!-- Create a form with the name "add_movie" -->
    <form name="add_movie" method="post" novalidate class="form">
        <div class="form__container">
            <!-- Include a hidden tag for the form -->
            {{ form.hidden_tag() }}

            <!-- Render the title, director, and year fields using the "render_text_field" macro -->
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            <!-- Render the cast, series, and tags fields using the "render_area_field" macro -->
            {{ render_area_field(form.cast) }}
            {{ render_area_field(form.series) }}
            {{ render_area_field(form.tags) }}

            <!-- Render the description and video link fields -->
            {{ render_area_field(form.description) }}
            {{ render_text_field(form.video_link) }}

            <!-- Add a submit button to the form -->
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>
{% endblock %}

movie_library/templates/new_movie.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <!-- Add a stylesheet for forms -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}"/>
{% endblock %}

{% block main_content %}
    <!-- Create a form with the name "add_movie" -->
    <form name="add_movie" method="post" novalidate class="form">
        <div class="form__container">
            <!-- Include a hidden tag for the form -->
            {{ form.hidden_tag() }}

            <!-- Render the title, director, and year fields using the "render_text_field" macro -->
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            <!-- Add a submit button to the form -->
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>
{% endblock %}

movie_library/templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <!-- Add a stylesheet for forms -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}"/>
{% endblock %}

{% block main_content %}
    <!-- Create a form with the name "register" -->
    <form name="register" method="post" novalidate class="form">
        <div class="form__container">
            <!-- Include a hidden tag for the form -->
            {{ form.hidden_tag() }}

            <!-- Render the email, password, and confirm password fields using the "render_text_field" macro -->
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}

            <!-- Add a small message for users with existing accounts -->
            <span class="form__small">
            Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
        </span>

            <!-- Add a submit button to the form -->
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>
{% endblock %}